export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";
export const AUTH_REGISTER_RESET = "AUTH_REGISTER_RESET";

export const AUTH_GET_ME_REQUEST = "AUTH_GET_ME_REQUEST";
export const AUTH_GET_ME_SUCCESS = "AUTH_GET_ME_SUCCESS";
export const AUTH_GET_ME_FAIL = "AUTH_GET_ME_FAIL";
export const AUTH_GET_ME_RESET = "AUTH_GET_ME_RESET";