export const SERVICE_GET_SERVICE_REVIEWS_REQUEST = "SERVICE_GET_SERVICE_REVIEWS_REQUEST";
export const SERVICE_GET_SERVICE_REVIEWS_SUCCESS = "SERVICE_GET_SERVICE_REVIEWS_SUCCESS";
export const SERVICE_GET_SERVICE_REVIEWS_FAIL = "SERVICE_GET_SERVICE_REVIEWS_FAIL";
export const SERVICE_GET_SERVICE_REVIEWS_RESET = "SERVICE_GET_SERVICE_REVIEWS_RESET";

export const SERVICE_ADD_REVIEW_REQUEST = "SERVICE_ADD_REVIEW_REQUEST";
export const SERVICE_ADD_REVIEW_SUCCESS = "SERVICE_ADD_REVIEW_SUCCESS";
export const SERVICE_ADD_REVIEW_FAIL = "SERVICE_ADD_REVIEW_FAIL";
export const SERVICE_ADD_REVIEW_RESET = "SERVICE_ADD_REVIEW_RESET";

export const SERVICE_REMOVE_REVIEW_REQUEST = "SERVICE_REMOVE_REVIEW_REQUEST";
export const SERVICE_REMOVE_REVIEW_SUCCESS = "SERVICE_REMOVE_REVIEW_SUCCESS";
export const SERVICE_REMOVE_REVIEW_FAIL = "SERVICE_REMOVE_REVIEW_FAIL";
export const SERVICE_REMOVE_REVIEW_RESET = "SERVICE_REMOVE_REVIEW_RESET";