export const SERVICE_GET_SERVICES_REQUEST = "SERVICE_GET_SERVICES_REQUEST";
export const SERVICE_GET_SERVICES_SUCCESS = "SERVICE_GET_SERVICES_SUCCESS";
export const SERVICE_GET_SERVICES_FAIL = "SERVICE_GET_SERVICES_FAIL";
export const SERVICE_GET_SERVICES_RESET = "SERVICE_GET_SERVICES_RESET";

export const SERVICE_GET_SERVICES_BY_DESCRIPTION_REQUEST = "SERVICE_GET_SERVICES_BY_DESCRIPTION_REQUEST";
export const SERVICE_GET_SERVICES_BY_DESCRIPTION_SUCCESS = "SERVICE_GET_SERVICES_BY_DESCRIPTION_SUCCESS";
export const SERVICE_GET_SERVICES_BY_DESCRIPTION_FAIL = "SERVICE_GET_SERVICES_BY_DESCRIPTION_FAIL";
export const SERVICE_GET_SERVICES_BY_DESCRIPTION_RESET = "SERVICE_GET_SERVICES_BY_DESCRIPTION_RESET";

export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_REQUEST = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_REQUEST";
export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_SUCCESS = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_SUCCESS";
export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_FAIL = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_FAIL";
export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_RESET = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_RESET";

export const ADD_FILTER = "ADD_FILTER";
export const CHANGE_PAGE_NUMBER = "CHANGE_PAGE_NUMBER";
export const RESET_PAGE_AND_FILTERS = "RESET_PAGE_AND_FILTERS";

export const SERVICE_GET_SERVICE_DETAILS_REQUEST = "SERVICE_GET_SERVICE_DETAILS_REQUEST";
export const SERVICE_GET_SERVICE_DETAILS_SUCCESS = "SERVICE_GET_SERVICE_DETAILS_SUCCESS";
export const SERVICE_GET_SERVICE_DETAILS_FAIL = "SERVICE_GET_SERVICE_DETAILS_FAIL";
export const SERVICE_GET_SERVICE_DETAILS_RESET = "SERVICE_GET_SERVICE_DETAILS_RESET";

export const SERVICE_GET_PRICE_PERCENTAGE_REQUEST = "SERVICE_GET_PRICE_PERCENTAGE_REQUEST";
export const SERVICE_GET_PRICE_PERCENTAGE_SUCCESS = "SERVICE_GET_PRICE_PERCENTAGE_SUCCESS";
export const SERVICE_GET_PRICE_PERCENTAGE_FAIL = "SERVICE_GET_PRICE_PERCENTAGE_FAIL";
export const SERVICE_GET_PRICE_PERCENTAGE_RESET = "SERVICE_GET_PRICE_PERCENTAGE_RESET";

export const SERVICE_GET_TOP_RATED_REQUEST = "SERVICE_GET_TOP_RATED_REQUEST";
export const SERVICE_GET_TOP_RATED_SUCCESS = "SERVICE_GET_TOP_RATED_SUCCESS";
export const SERVICE_GET_TOP_RATED_FAIL = "SERVICE_GET_TOP_RATED_FAIL";
export const SERVICE_GET_TOP_RATED_RESET = "SERVICE_GET_TOP_RATED_RESET";

export const SERVICE_GET_MY_SERVICES_REQUEST = "SERVICE_GET_MY_SERVICES_REQUEST";
export const SERVICE_GET_MY_SERVICES_SUCCESS = "SERVICE_GET_MY_SERVICES_SUCCESS";
export const SERVICE_GET_MY_SERVICES_FAIL = "SERVICE_GET_MY_SERVICES_FAIL";
export const SERVICE_GET_MY_SERVICES_RESET = "SERVICE_GET_MY_SERVICES_RESET";

export const SERVICE_POST_REQUEST = "SERVICE_POST_REQUEST";
export const SERVICE_POST_SUCCESS = "SERVICE_POST_SUCCESS";
export const SERVICE_POST_FAIL = "SERVICE_POST_FAIL";
export const SERVICE_POST_RESET = "SERVICE_POST_RESET";

export const SERVICE_UPDATE_REQUEST = "SERVICE_UPDATE_REQUEST";
export const SERVICE_UPDATE_SUCCESS = "SERVICE_UPDATE_SUCCESS";
export const SERVICE_UPDATE_FAIL = "SERVICE_UPDATE_FAIL";
export const SERVICE_UPDATE_RESET = "SERVICE_UPDATE_RESET";

export const SERVICE_DELETE_REQUEST = "SERVICE_DELETE_REQUEST";
export const SERVICE_DELETE_SUCCESS = "SERVICE_DELETE_SUCCESS";
export const SERVICE_DELETE_FAIL = "SERVICE_DELETE_FAIL";
export const SERVICE_DELETE_RESET = "SERVICE_DELETE_RESET";

export const SERVICE_ADD_AVAILABILITY_PERIODS_REQUEST = "SERVICE_ADD_AVAILABILITY_PERIODS_REQUEST";
export const SERVICE_ADD_AVAILABILITY_PERIODS_SUCCESS = "SERVICE_ADD_AVAILABILITY_PERIODS_SUCCESS";
export const SERVICE_ADD_AVAILABILITY_PERIODS_FAIL = "SERVICE_ADD_AVAILABILITY_PERIODS_FAIL";
export const SERVICE_ADD_AVAILABILITY_PERIODS_RESET = "SERVICE_ADD_AVAILABILITY_PERIODS_RESET";

export const SERVICE_REMOVE_AVAILABILITY_PERIODS_REQUEST = "SERVICE_REMOVE_AVAILABILITY_PERIODS_REQUEST";
export const SERVICE_REMOVE_AVAILABILITY_PERIODS_SUCCESS = "SERVICE_REMOVE_AVAILABILITY_PERIODS_SUCCESS";
export const SERVICE_REMOVE_AVAILABILITY_PERIODS_FAIL = "SERVICE_REMOVE_AVAILABILITY_PERIODS_FAIL";
export const SERVICE_REMOVE_AVAILABILITY_PERIODS_RESET = "SERVICE_REMOVE_AVAILABILITY_PERIODS_RESET";

export const SERVICE_ADD_PAYMENT_USERS_REQUEST = "SERVICE_ADD_PAYMENT_USERS_REQUEST";
export const SERVICE_ADD_PAYMENT_USERS_SUCCESS = "SERVICE_ADD_PAYMENT_USERS_SUCCESS";
export const SERVICE_ADD_PAYMENT_USERS_FAIL = "SERVICE_ADD_PAYMENT_USERS_FAIL";
export const SERVICE_ADD_PAYMENT_USERS_RESET = "SERVICE_ADD_PAYMENT_USERS_RESET";

export const SERVICE_UPLOAD_IMAGES_REQUEST = "SERVICE_UPLOAD_IMAGES_REQUEST";
export const SERVICE_UPLOAD_IMAGES_SUCCESS = "SERVICE_UPLOAD_IMAGES_SUCCESS";
export const SERVICE_UPLOAD_IMAGES_FAIL = "SERVICE_UPLOAD_IMAGES_FAIL";
export const SERVICE_UPLOAD_IMAGES_RESET = "SERVICE_UPLOAD_IMAGES_RESET";