export const SERVICE_GET_SERVICES_REQUEST = "SERVICE_GET_SERVICES_REQUEST";
export const SERVICE_GET_SERVICES_SUCCESS = "SERVICE_GET_SERVICES_SUCCESS";
export const SERVICE_GET_SERVICES_FAIL = "SERVICE_GET_SERVICES_FAIL";
export const SERVICE_GET_SERVICES_RESET = "SERVICE_GET_SERVICES_RESET";