export const SERVICE_GET_SERVICES_REQUEST = "SERVICE_GET_SERVICES_REQUEST";
export const SERVICE_GET_SERVICES_SUCCESS = "SERVICE_GET_SERVICES_SUCCESS";
export const SERVICE_GET_SERVICES_FAIL = "SERVICE_GET_SERVICES_FAIL";
export const SERVICE_GET_SERVICES_RESET = "SERVICE_GET_SERVICES_RESET";

export const SERVICE_GET_SERVICES_BY_DESCRIPTION_REQUEST = "SERVICE_GET_SERVICES_BY_DESCRIPTION_REQUEST";
export const SERVICE_GET_SERVICES_BY_DESCRIPTION_SUCCESS = "SERVICE_GET_SERVICES_BY_DESCRIPTION_SUCCESS";
export const SERVICE_GET_SERVICES_BY_DESCRIPTION_FAIL = "SERVICE_GET_SERVICES_BY_DESCRIPTION_FAIL";
export const SERVICE_GET_SERVICES_BY_DESCRIPTION_RESET = "SERVICE_GET_SERVICES_BY_DESCRIPTION_RESET";

export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_REQUEST = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_REQUEST";
export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_SUCCESS = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_SUCCESS";
export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_FAIL = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_FAIL";
export const SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_RESET = "SERVICE_GET_SERVICES_IN_DISTANCE_RADIUS_RESET";

export const ADD_FILTER = "ADD_FILTER";
export const CHANGE_PAGE_NUMBER = "CHANGE_PAGE_NUMBER";
export const RESET_PAGE_AND_FILTERS = "RESET_PAGE_AND_FILTERS";

export const SERVICE_GET_SERVICE_DETAILS_REQUEST = "SERVICE_GET_SERVICE_DETAILS_REQUEST";
export const SERVICE_GET_SERVICE_DETAILS_SUCCESS = "SERVICE_GET_SERVICE_DETAILS_SUCCESS";
export const SERVICE_GET_SERVICE_DETAILS_FAIL = "SERVICE_GET_SERVICE_DETAILS_FAIL";
export const SERVICE_GET_SERVICE_DETAILS_RESET = "SERVICE_GET_SERVICE_DETAILS_RESET";

export const SERVICE_GET_PRICE_PERCENTAGE_REQUEST = "SERVICE_GET_PRICE_PERCENTAGE_REQUEST";
export const SERVICE_GET_PRICE_PERCENTAGE_SUCCESS = "SERVICE_GET_PRICE_PERCENTAGE_SUCCESS";
export const SERVICE_GET_PRICE_PERCENTAGE_FAIL = "SERVICE_GET_PRICE_PERCENTAGE_FAIL";
export const SERVICE_GET_PRICE_PERCENTAGE_RESET = "SERVICE_GET_PRICE_PERCENTAGE_RESET";

export const SERVICE_GET_TOP_RATED_REQUEST = "SERVICE_GET_TOP_RATED_REQUEST";
export const SERVICE_GET_TOP_RATED_SUCCESS = "SERVICE_GET_TOP_RATED_SUCCESS";
export const SERVICE_GET_TOP_RATED_FAIL = "SERVICE_GET_TOP_RATED_FAIL";
export const SERVICE_GET_TOP_RATED_RESET = "SERVICE_GET_TOP_RATED_RESET";

export const SERVICE_GET_MY_SERVICES_REQUEST = "SERVICE_GET_MY_SERVICES_REQUEST";
export const SERVICE_GET_MY_SERVICES_SUCCESS = "SERVICE_GET_MY_SERVICES_SUCCESS";
export const SERVICE_GET_MY_SERVICES_FAIL = "SERVICE_GET_MY_SERVICES_FAIL";
export const SERVICE_GET_MY_SERVICES_RESET = "SERVICE_GET_MY_SERVICES_RESET";