export const USER_UPDATE_PROFILE_INFO_REQUEST = "USER_UPDATE_PROFILE_INFO_REQUEST";
export const USER_UPDATE_PROFILE_INFO_SUCCESS = "USER_UPDATE_PROFILE_INFO_SUCCESS";
export const USER_UPDATE_PROFILE_INFO_FAIL = "USER_UPDATE_PROFILE_INFO_FAIL";
export const USER_UPDATE_PROFILE_INFO_RESET = "USER_UPDATE_PROFILE_INFO_RESET";

export const USER_UPLOAD_PROFILE_PICTURE_REQUEST = "USER_UPLOAD_PROFILE_PICTURE_REQUEST";
export const USER_UPLOAD_PROFILE_PICTURE_SUCCESS = "USER_UPLOAD_PROFILE_PICTURE_SUCCESS";
export const USER_UPLOAD_PROFILE_PICTURE_FAIL = "USER_UPLOAD_PROFILE_PICTURE_FAIL";
export const USER_UPLOAD_PROFILE_PICTURE_RESET = "USER_UPLOAD_PROFILE_PICTURE_RESET";

export const USER_SET_SCHEDULE_COMPLETED_REQUEST = "USER_SET_SCHEDULE_COMPLETED_REQUEST";
export const USER_SET_SCHEDULE_COMPLETED_SUCCESS = "USER_SET_SCHEDULE_COMPLETED_SUCCESS";
export const USER_SET_SCHEDULE_COMPLETED_FAIL = "USER_SET_SCHEDULE_COMPLETED_FAIL";
export const USER_SET_SCHEDULE_COMPLETED_RESET = "USER_SET_SCHEDULE_COMPLETED_RESET";